//
//  Pokedex.m
//  PokeScan
//
//  Created by Ralph Schön on 24.07.16.
//  Copyright © 2016 Ralph Schön. All rights reserved.
//

#import "Pokedex.h"

@implementation Pokedex

- (instancetype)init {
    self = [super init];
    
    _pokedexList = @[@[@"empty", @"http://pokewiki.de/images/e/ea/Pok%C3%A9mon-Icon_201.png"],
                     @[@"Bisasam", @"http://pokewiki.de/images/1/1c/Pok%C3%A9mon-Icon_001.png"],
                     @[@"Bisaknosp", @"http://pokewiki.de/images/1/1f/Pok%C3%A9mon-Icon_002.png"],
                     @[@"Bisaflor", @"http://pokewiki.de/images/2/2e/Pok%C3%A9mon-Icon_003.png"],
                     @[@"Glumanda", @"http://pokewiki.de/images/0/07/Pok%C3%A9mon-Icon_004.png"],
                     @[@"Glutexo", @"http://pokewiki.de/images/d/d3/Pok%C3%A9mon-Icon_005.png"],
                     @[@"Glurak", @"http://pokewiki.de/images/7/73/Pok%C3%A9mon-Icon_006.png"],
                     @[@"Schiggy", @"http://pokewiki.de/images/d/de/Pok%C3%A9mon-Icon_007.png"],
                     @[@"Schillok", @"http://pokewiki.de/images/6/68/Pok%C3%A9mon-Icon_008.png"],
                     @[@"Turtok", @"http://pokewiki.de/images/d/d8/Pok%C3%A9mon-Icon_009.png"],
                     @[@"Raupy", @"http://pokewiki.de/images/b/b2/Pok%C3%A9mon-Icon_010.png"],
                     @[@"Safcon", @"http://pokewiki.de/images/c/c4/Pok%C3%A9mon-Icon_011.png"],
                     @[@"Smettbo", @"http://pokewiki.de/images/c/c9/Pok%C3%A9mon-Icon_012.png"],
                     @[@"Hornliu", @"http://pokewiki.de/images/1/1a/Pok%C3%A9mon-Icon_013.png"],
                     @[@"Kokuna", @"http://pokewiki.de/images/d/d9/Pok%C3%A9mon-Icon_014.png"],
                     @[@"Bibor", @"http://pokewiki.de/images/8/8d/Pok%C3%A9mon-Icon_015.png"],
                     @[@"Taubsi", @"http://pokewiki.de/images/5/5f/Pok%C3%A9mon-Icon_016.png"],
                     @[@"Tauboga", @"http://pokewiki.de/images/1/1d/Pok%C3%A9mon-Icon_017.png"],
                     @[@"Tauboss", @"http://pokewiki.de/images/5/5b/Pok%C3%A9mon-Icon_018.png"],
                     @[@"Rattfratz", @"http://pokewiki.de/images/9/9d/Pok%C3%A9mon-Icon_019.png"],
                     @[@"Rattikarl", @"http://pokewiki.de/images/d/d2/Pok%C3%A9mon-Icon_020.png"],
                     @[@"Habitak", @"http://pokewiki.de/images/b/bc/Pok%C3%A9mon-Icon_021.png"],
                     @[@"Ibitak", @"http://pokewiki.de/images/f/f6/Pok%C3%A9mon-Icon_022.png"],
                     @[@"Rettan", @"http://pokewiki.de/images/8/8a/Pok%C3%A9mon-Icon_023.png"],
                     @[@"Arbok", @"http://pokewiki.de/images/5/5c/Pok%C3%A9mon-Icon_024.png"],
                     @[@"Pikachu", @"http://pokewiki.de/images/1/17/Pok%C3%A9mon-Icon_025.png"],
                     @[@"Raichu", @"http://pokewiki.de/images/4/41/Pok%C3%A9mon-Icon_026.png"],
                     @[@"Sandan", @"http://pokewiki.de/images/3/3c/Pok%C3%A9mon-Icon_027.png"],
                     @[@"Sandamer", @"http://pokewiki.de/images/2/2a/Pok%C3%A9mon-Icon_028.png"],
                     @[@"Nidoran f", @"http://pokewiki.de/images/a/a1/Pok%C3%A9mon-Icon_029.png"],
                     @[@"Nidorina",  @"http://pokewiki.de/images/2/20/Pok%C3%A9mon-Icon_030.png"],
                     @[@"Nidoqueen", @"http://pokewiki.de/images/d/d3/Pok%C3%A9mon-Icon_031.png"],
                     @[@"Nidoran m", @"http://pokewiki.de/images/b/b8/Pok%C3%A9mon-Icon_032.png"],
                     @[@"Nidorino", @"http://pokewiki.de/images/b/b9/Pok%C3%A9mon-Icon_033.png"],
                     @[@"Nidoking", @"http://pokewiki.de/images/a/a8/Pok%C3%A9mon-Icon_034.png"],
                     @[@"Piepi", @"http://pokewiki.de/images/1/11/Pok%C3%A9mon-Icon_035.png"],
                     @[@"Pixi", @"http://pokewiki.de/images/7/7e/Pok%C3%A9mon-Icon_036.png"],
                     @[@"Vulpix", @"http://pokewiki.de/images/f/fe/Pok%C3%A9mon-Icon_037.png"],
                     @[@"Vulnona", @"http://pokewiki.de/images/4/4c/Pok%C3%A9mon-Icon_038.png"],
                     @[@"Pummeluff", @"http://pokewiki.de/images/7/7e/Pok%C3%A9mon-Icon_039.png"],
                     @[@"Knuddeluff", @"http://pokewiki.de/images/1/15/Pok%C3%A9mon-Icon_040.png"],
                     @[@"Zubat", @"http://pokewiki.de/images/a/ac/Pok%C3%A9mon-Icon_041.png"],
                     @[@"Golbat", @"http://pokewiki.de/images/f/fd/Pok%C3%A9mon-Icon_042.png"],
                     @[@"Myrapla", @"http://pokewiki.de/images/3/3a/Pok%C3%A9mon-Icon_043.png"],
                     @[@"Duflor", @"http://pokewiki.de/images/b/b7/Pok%C3%A9mon-Icon_044.png"],
                     @[@"Giflor", @"http://pokewiki.de/images/e/e2/Pok%C3%A9mon-Icon_045.png"],
                     @[@"Paras", @"http://pokewiki.de/images/9/97/Pok%C3%A9mon-Icon_046.png"],
                     @[@"Parasek", @"http://pokewiki.de/images/f/f9/Pok%C3%A9mon-Icon_047.png"],
                     @[@"Bluzuk", @"http://pokewiki.de/images/7/77/Pok%C3%A9mon-Icon_048.png"],
                     @[@"Omot", @"http://pokewiki.de/images/5/5e/Pok%C3%A9mon-Icon_049.png"],
                     @[@"Digda", @"http://pokewiki.de/images/7/7c/Pok%C3%A9mon-Icon_050.png"],
                     @[@"Digdri", @"http://pokewiki.de/images/2/2e/Pok%C3%A9mon-Icon_051.png"],
                     @[@"Mauzi", @"http://pokewiki.de/images/0/05/Pok%C3%A9mon-Icon_052.png"],
                     @[@"Snobilikat", @"http://pokewiki.de/images/a/a6/Pok%C3%A9mon-Icon_053.png"],
                     @[@"Enton", @"http://pokewiki.de/images/d/df/Pok%C3%A9mon-Icon_054.png"],
                     @[@"Entoron", @"http://pokewiki.de/images/9/9f/Pok%C3%A9mon-Icon_055.png"],
                     @[@"Menki", @"http://pokewiki.de/images/4/42/Pok%C3%A9mon-Icon_056.png"],
                     @[@"Rasaff", @"http://pokewiki.de/images/0/0c/Pok%C3%A9mon-Icon_057.png"],
                     @[@"Fukano", @"http://pokewiki.de/images/3/3f/Pok%C3%A9mon-Icon_058.png"],
                     @[@"Arkani", @"http://pokewiki.de/images/d/d8/Pok%C3%A9mon-Icon_059.png"],
                     @[@"Quapsel", @"http://pokewiki.de/images/6/6c/Pok%C3%A9mon-Icon_060.png"],
                     @[@"Quaputzi", @"http://pokewiki.de/images/e/e5/Pok%C3%A9mon-Icon_061.png"],
                     @[@"Quappo", @"http://pokewiki.de/images/c/c2/Pok%C3%A9mon-Icon_062.png"],
                     @[@"Abra", @"http://pokewiki.de/images/7/7c/Pok%C3%A9mon-Icon_063.png"],
                     @[@"Kadabra", @"http://pokewiki.de/images/a/a7/Pok%C3%A9mon-Icon_064.png"],
                     @[@"Simsala", @"http://pokewiki.de/images/3/38/Pok%C3%A9mon-Icon_065.png"],
                     @[@"Machollo", @"http://pokewiki.de/images/f/fc/Pok%C3%A9mon-Icon_066.png"],
                     @[@"Maschock", @"http://pokewiki.de/images/1/17/Pok%C3%A9mon-Icon_067.png"],
                     @[@"Machomei", @"http://pokewiki.de/images/d/d0/Pok%C3%A9mon-Icon_068.png"],
                     @[@"Knofensa", @"http://pokewiki.de/images/0/00/Pok%C3%A9mon-Icon_069.png"],
                     @[@"Ultrigaria", @"http://pokewiki.de/images/0/01/Pok%C3%A9mon-Icon_070.png"],
                     @[@"Sarzenia", @"http://pokewiki.de/images/8/84/Pok%C3%A9mon-Icon_071.png"],
                     @[@"Tentacha", @"http://pokewiki.de/images/7/7d/Pok%C3%A9mon-Icon_072.png"],
                     @[@"Tentoxa", @"http://pokewiki.de/images/6/6d/Pok%C3%A9mon-Icon_073.png"],
                     @[@"Kleinstein", @"http://pokewiki.de/images/9/98/Pok%C3%A9mon-Icon_074.png"],
                     @[@"Georok", @"http://pokewiki.de/images/6/65/Pok%C3%A9mon-Icon_075.png"],
                     @[@"Geowaz", @"http://pokewiki.de/images/3/39/Pok%C3%A9mon-Icon_076.png"],
                     @[@"Ponita", @"http://pokewiki.de/images/1/1f/Pok%C3%A9mon-Icon_077.png"],
                     @[@"Gallopa", @"http://pokewiki.de/images/5/56/Pok%C3%A9mon-Icon_078.png"],
                     @[@"Flegmon", @"http://pokewiki.de/images/d/dd/Pok%C3%A9mon-Icon_079.png"],
                     @[@"Lahmus", @"http://pokewiki.de/images/c/c3/Pok%C3%A9mon-Icon_080.png"],
                     @[@"Magnetilo", @"http://pokewiki.de/images/2/22/Pok%C3%A9mon-Icon_081.png"],
                     @[@"Magneton", @"http://pokewiki.de/images/a/a4/Pok%C3%A9mon-Icon_082.png"],
                     @[@"Porenta", @"http://pokewiki.de/images/9/9e/Pok%C3%A9mon-Icon_083.png"],
                     @[@"Dodu", @"http://pokewiki.de/images/7/73/Pok%C3%A9mon-Icon_084.png"],
                     @[@"Dodri", @"http://pokewiki.de/images/5/50/Pok%C3%A9mon-Icon_085.png"],
                     @[@"Jurob", @"http://pokewiki.de/images/c/c8/Pok%C3%A9mon-Icon_086.png"],
                     @[@"Jugong", @"http://pokewiki.de/images/7/71/Pok%C3%A9mon-Icon_087.png"],
                     @[@"Sleima", @"http://pokewiki.de/images/1/1b/Pok%C3%A9mon-Icon_088.png"],
                     @[@"Sleimok", @"http://pokewiki.de/images/d/d6/Pok%C3%A9mon-Icon_089.png"],
                     @[@"Muschas", @"http://pokewiki.de/images/5/5b/Pok%C3%A9mon-Icon_090.png"],
                     @[@"Austos", @"http://pokewiki.de/images/a/aa/Pok%C3%A9mon-Icon_091.png"],
                     @[@"Nebulak", @"http://pokewiki.de/images/a/ab/Pok%C3%A9mon-Icon_092.png"],
                     @[@"Alpollo", @"http://pokewiki.de/images/f/f2/Pok%C3%A9mon-Icon_093.png"],
                     @[@"Gengar", @"http://pokewiki.de/images/4/45/Pok%C3%A9mon-Icon_094.png"],
                     @[@"Onix", @"http://pokewiki.de/images/5/5a/Pok%C3%A9mon-Icon_095.png"],
                     @[@"Traumato", @"http://pokewiki.de/images/b/bf/Pok%C3%A9mon-Icon_096.png"],
                     @[@"Hypno", @"http://pokewiki.de/images/7/71/Pok%C3%A9mon-Icon_097.png"],
                     @[@"Krabby", @"http://pokewiki.de/images/0/00/Pok%C3%A9mon-Icon_098.png"],
                     @[@"Kingler", @"http://pokewiki.de/images/6/66/Pok%C3%A9mon-Icon_099.png"],
                     @[@"Voltobal", @"http://pokewiki.de/images/9/9d/Pok%C3%A9mon-Icon_100.png"],
                     @[@"Lektrobal", @"http://pokewiki.de/images/0/00/Pok%C3%A9mon-Icon_101.png"],
                     @[@"Owei", @"http://pokewiki.de/images/8/81/Pok%C3%A9mon-Icon_102.png"],
                     @[@"Kokowei", @"http://pokewiki.de/images/5/5c/Pok%C3%A9mon-Icon_103.png"],
                     @[@"Tragosso", @"http://pokewiki.de/images/3/33/Pok%C3%A9mon-Icon_104.png"],
                     @[@"Knogga", @"http://pokewiki.de/images/c/c6/Pok%C3%A9mon-Icon_105.png"],
                     @[@"Kicklee", @"http://pokewiki.de/images/6/66/Pok%C3%A9mon-Icon_106.png"],
                     @[@"Nockchan", @"http://pokewiki.de/images/9/92/Pok%C3%A9mon-Icon_107.png"],
                     @[@"Schlurp", @"http://pokewiki.de/images/1/15/Pok%C3%A9mon-Icon_108.png"],
                     @[@"Smogon", @"http://pokewiki.de/images/7/73/Pok%C3%A9mon-Icon_109.png"],
                     @[@"Smogmog", @"http://pokewiki.de/images/1/1b/Pok%C3%A9mon-Icon_110.png"],
                     @[@"Rihorn", @"http://pokewiki.de/images/4/44/Pok%C3%A9mon-Icon_111.png"],
                     @[@"Rizeros", @"http://pokewiki.de/images/5/51/Pok%C3%A9mon-Icon_112.png"],
                     @[@"Chaneira", @"http://pokewiki.de/images/4/4d/Pok%C3%A9mon-Icon_113.png"],
                     @[@"Tangela", @"http://pokewiki.de/images/2/2c/Pok%C3%A9mon-Icon_114.png"],
                     @[@"Kangmama", @"http://pokewiki.de/images/6/6f/Pok%C3%A9mon-Icon_115.png"],
                     @[@"Seeper", @"http://pokewiki.de/images/e/e7/Pok%C3%A9mon-Icon_116.png"],
                     @[@"Seemon", @"http://pokewiki.de/images/7/71/Pok%C3%A9mon-Icon_117.png"],
                     @[@"Goldini", @"http://pokewiki.de/images/e/e4/Pok%C3%A9mon-Icon_118.png"],
                     @[@"Golking", @"http://pokewiki.de/images/6/61/Pok%C3%A9mon-Icon_119.png"],
                     @[@"Sterndu", @"http://pokewiki.de/images/c/ce/Pok%C3%A9mon-Icon_120.png"],
                     @[@"Starmie", @"http://pokewiki.de/images/c/cb/Pok%C3%A9mon-Icon_121.png"],
                     @[@"Pantimos", @"http://pokewiki.de/images/6/60/Pok%C3%A9mon-Icon_122.png"],
                     @[@"Sichlor", @"http://pokewiki.de/images/3/33/Pok%C3%A9mon-Icon_123.png"],
                     @[@"Rossana", @"http://pokewiki.de/images/7/74/Pok%C3%A9mon-Icon_124.png"],
                     @[@"Elektek", @"http://pokewiki.de/images/e/eb/Pok%C3%A9mon-Icon_125.png"],
                     @[@"Magmar", @"http://pokewiki.de/images/b/b5/Pok%C3%A9mon-Icon_126.png"],
                     @[@"Pinsir", @"http://pokewiki.de/images/4/44/Pok%C3%A9mon-Icon_127.png"],
                     @[@"Tauros", @"http://pokewiki.de/images/e/e0/Pok%C3%A9mon-Icon_128.png"],
                     @[@"Karpador", @"http://pokewiki.de/images/e/e3/Pok%C3%A9mon-Icon_129.png"],
                     @[@"Garados", @"http://pokewiki.de/images/9/99/Pok%C3%A9mon-Icon_130.png"],
                     @[@"Lapras", @"http://pokewiki.de/images/a/a8/Pok%C3%A9mon-Icon_131.png"],
                     @[@"Ditto", @"http://pokewiki.de/images/3/31/Pok%C3%A9mon-Icon_132.png"],
                     @[@"Evoli", @"http://pokewiki.de/images/1/12/Pok%C3%A9mon-Icon_133.png"],
                     @[@"Aquana", @"http://pokewiki.de/images/e/e3/Pok%C3%A9mon-Icon_134.png"],
                     @[@"Blitza", @"http://pokewiki.de/images/0/0f/Pok%C3%A9mon-Icon_135.png"],
                     @[@"Flamara", @"http://pokewiki.de/images/d/d7/Pok%C3%A9mon-Icon_136.png"],
                     @[@"Porygon", @"http://pokewiki.de/images/7/7e/Pok%C3%A9mon-Icon_137.png"],
                     @[@"Amonitas", @"http://pokewiki.de/images/0/0f/Pok%C3%A9mon-Icon_138.png"],
                     @[@"Amoroso", @"http://pokewiki.de/images/3/34/Pok%C3%A9mon-Icon_139.png"],
                     @[@"Kabuto", @"http://pokewiki.de/images/7/7f/Pok%C3%A9mon-Icon_140.png"],
                     @[@"Kabutops", @"http://pokewiki.de/images/f/f0/Pok%C3%A9mon-Icon_141.png"],
                     @[@"Aerodactyl", @"http://pokewiki.de/images/9/9d/Pok%C3%A9mon-Icon_142.png"],
                     @[@"Relaxo", @"http://pokewiki.de/images/d/d2/Pok%C3%A9mon-Icon_143.png"],
                     @[@"Arktos", @"http://pokewiki.de/images/0/04/Pok%C3%A9mon-Icon_144.png"],
                     @[@"Zapdos", @"http://pokewiki.de/images/f/ff/Pok%C3%A9mon-Icon_145.png"],
                     @[@"Lavados", @"http://pokewiki.de/images/4/4d/Pok%C3%A9mon-Icon_146.png"],
                     @[@"Dratini", @"http://pokewiki.de/images/8/80/Pok%C3%A9mon-Icon_147.png"],
                     @[@"Dragonir", @"http://pokewiki.de/images/3/30/Pok%C3%A9mon-Icon_148.png"],
                     @[@"Dragoran", @"http://pokewiki.de/images/d/dd/Pok%C3%A9mon-Icon_149.png"],
                     @[@"Mewtu", @"http://pokewiki.de/images/9/92/Pok%C3%A9mon-Icon_150.png"],
                     @[@"Mew", @"http://pokewiki.de/images/a/aa/Pok%C3%A9mon-Icon_151.png"]];
    
    return self;
}

@end
